### ISSUE TITLE
IP Filtering improvement required

### ISSUE THREAD

**Issue by florian0** [florian0/MiniBillingServer#3]
The code cannot handle complex return values of `RemoteEndPoint.ToString()` like `[::1]:12927`

Problematic code: 
* https://github.com/florian0/MiniBillingServer/blob/master/Handlers/ServerStateHandler.cs#L15
* https://github.com/florian0/MiniBillingServer/blob/master/Handlers/SilkDataCallHandler.cs#L34

**Comment by devtekve** [comment]
Is it corrected already?

**Comment by florian0** [comment]
No, i haven't even looked into it.
Might be sufficient to use
```
context.Request.RemoteEndPoint.IPAddress.ToString();
```

**Comment by florian0** [comment]
Made a branch with improved filtering.
https://github.com/florian0/MiniBillingServer/commit/667f7edae35ebfae5096a33fa2f46dddd6f8cdc1

**Comment by florian0** [comment]
Fixed in commit 8953310
