### ISSUE TITLE
BillingServer is Dead!!

### ISSUE THREAD

**Issue by ntirado89** [florian0/MiniBillingServer#6]
Run in my server test, and have a problem: ShardManager module crash!.

Image: the first url request is in browser (return 1, Ok!), the second request is open ShardManager and crash!.
[http://prntscr.com/bm29i6](http://prntscr.com/bm29i6)

**Comment by florian0** [comment]
Weird. Can you change the following lines in ServerStateHandler.cs from
```
// Validate Handler
if (context.Request.Url.LocalPath.ToLower() != "/billing_silkdatacall.asp")
{
    return false;
}
```
to
```
// Validate Handler
if (context.Request.Url.LocalPath.ToLower() != "/billing_silkdatacall.asp")
{
    Console.WriteLine("Not responsible for: {0} | {1}", context.Request.Url.ToString(), context.Request.Url.LocalPath.ToLower());
    return false;
}
```
and post the output after the ShardManager crashed?

**Comment by florian0** [comment]
Also, are you using the latest version?

**Comment by florian0** [comment]
closed since no answer
